
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/predictionDB
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

dataJson:
  url: https://raw.githubusercontent.com/aniket7777777/cricpred/master/Data_Matches.json